export const GET_LOGIN_REQUEST = "GET_LOGIN_REQUEST";
export const GET_LOGIN_SUCCESS = "get_LOGIN_SUCCESS"
export const GET_LOGIN_FAILURE = "get_LOGIN_FAILURE"


export const GET_LOGOUT = "GET_LOGOUT";

export const SET_USER_DATA = "SET_USER_DATA";

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE"

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE"


export const REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST"
export const REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS"
export const REMOVE_FROM_CART_FAILURE = "REMOVE_FROM_CART_FAILURE"

export const GET_CART_REQUEST = "GET_CART_REQUEST"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"
export const GET_CART_FAILURE = "GET_CART_FAILURE"

export const ADD_TO_WISHLIST_REQUEST = "ADD_TO_WISHLIST_REQUEST"
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS"
export const ADD_TO_WISHLIST_FAILURE = "ADD_TO_WISHLIST_FAILURE"


export const TOTAL_PAGES = "TOTAL_PAGES"
export const CURRENT_PAGE = "CURRENT_PAGE"


export const GET_SINGLE_REQUEST = "GET_SINGLE_REQUEST"
export const GET_SINGLE_SUCCESS = "GET_SINGLE_SUCCESS"
export const GET_SINGLE_FAILURE = "GET_SINGLE_FAILURE"


export const CLEAR_CART_ITEMS = "CLEAR_CART_ITEMS"
export const CLEAR_CART_ITEMS_SUCCESS = "CLEAR_CART_ITEMS_SUCCESS"
export const CLEAR_CART_ITEMS_FAILURE = "CLEAR_CART_ITEMS_FAILURE"


export const GET_SEARCH_REQUEST = "GET_SEARCH_REQUEST";
export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS";
export const GET_SEARCH_FALURE = "GET_SEARCH_FALURE";

export const GET_WISHLIST_ITEMS = "GET_WISHLIST_ITEMS";
export const GET_WISHLIST_SUCCESS = "GET_WISHLIST_SUCCESS";
export const GET_WISHLIST_FAILURE = "GET_WISHLIST_FAILURE";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";

export const url = 'https://ecommerce-eb1o.onrender.com'
// export const url = 'http://localhost:4500'