export const GET_LOGIN_REQUEST = "GET_LOGIN_REQUEST";
export const GET_LOGIN_SUCCESS = "get_LOGIN_SUCCESS"
export const GET_LOGIN_FAILURE = "get_LOGIN_FAILURE"


export const GET_LOGOUT = "GET_LOGOUT";

export const SET_USER_DATA = "SET_USER_DATA";  

export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE"

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE"

export const GET_CART_REQUEST = "GET_CART_REQUEST"
export const GET_CART_SUCCESS = "GET_CART_SUCCESS"
export const GET_CART_FAILURE = "GET_CART_FAILURE"

export const ADD_TO_WISHLIST_REQUEST = "ADD_TO_WISHLIST_REQUEST"
export const ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS"
export const ADD_TO_WISHLIST_FAILURE = "ADD_TO_WISHLIST_FAILURE"


export const url = 'https://ecommerce-eb1o.onrender.com'
// export const url = 'http://localhost:4500'